<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.O.U3CCR' shared service.

return $this->privates['.service_locator.O.U3CCR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'fraisRepository' => ['privates', 'App\\Repository\\FraisRepository', 'getFraisRepositoryService.php', true],
], [
    'fraisRepository' => 'App\\Repository\\FraisRepository',
]);
