#vich_uploader:
   # db_driver: orm

    #mappings:
       # property_image:
            #uri_prefix: /images/property_image
            #upload_destination: '%kernel.project_dir%/public/images/property_image'

            #inject_on_load : false 
            #delete_on_update : true 
            #delete_on_remove : true
