<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wSyEu85' shared service.

return $this->privates['.service_locator.wSyEu85'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'frai' => ['privates', '.errored..service_locator.wSyEu85.App\\Entity\\Frais', NULL, 'Cannot autowire service ".service_locator.wSyEu85": it references class "App\\Entity\\Frais" but no such service exists.'],
], [
    'frai' => 'App\\Entity\\Frais',
]);
