<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yC11jyM' shared service.

return $this->privates['.service_locator.yC11jyM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'user' => ['privates', '.errored..service_locator.yC11jyM.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.yC11jyM": it references class "App\\Entity\\User" but no such service exists.'],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'serializer' => '?',
    'user' => 'App\\Entity\\User',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
