<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA0zN0qx\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA0zN0qx/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerA0zN0qx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerA0zN0qx\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerA0zN0qx\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'A0zN0qx',
    'container.build_id' => '415f3e19',
    'container.build_time' => 1565099852,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA0zN0qx');
