<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'compte_partenaire_index' => [[], ['_controller' => 'App\\Controller\\ComptePartenaireController::index'], [], [['text', '/compte/partenaire/']], [], []],
    'compte_partenaire_new' => [[], ['_controller' => 'App\\Controller\\ComptePartenaireController::new'], [], [['text', '/compte/partenaire/new']], [], []],
    'compte_partenaire_show' => [['id'], ['_controller' => 'App\\Controller\\ComptePartenaireController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/compte/partenaire']], [], []],
    'compte_partenaire_edit' => [['id'], ['_controller' => 'App\\Controller\\ComptePartenaireController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/compte/partenaire']], [], []],
    'compte_partenaire_delete' => [['id'], ['_controller' => 'App\\Controller\\ComptePartenaireController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/compte/partenaire']], [], []],
    'depot_index' => [[], ['_controller' => 'App\\Controller\\DepotController::index'], [], [['text', '/depot/']], [], []],
    'depot_new' => [[], ['_controller' => 'App\\Controller\\DepotController::new'], [], [['text', '/depot/new']], [], []],
    'depot_show' => [['id'], ['_controller' => 'App\\Controller\\DepotController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/depot']], [], []],
    'depot_edit' => [['id'], ['_controller' => 'App\\Controller\\DepotController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/depot']], [], []],
    'depot_delete' => [['id'], ['_controller' => 'App\\Controller\\DepotController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/depot']], [], []],
    'partenaire_index' => [[], ['_controller' => 'App\\Controller\\PartenaireController::index'], [], [['text', '/partenaire/']], [], []],
    'partenaire_new' => [[], ['_controller' => 'App\\Controller\\PartenaireController::ajout'], [], [['text', '/partenaire/new']], [], []],
    'partenaire_show' => [['id'], ['_controller' => 'App\\Controller\\PartenaireController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/partenaire']], [], []],
    'partenaire_edit' => [['id'], ['_controller' => 'App\\Controller\\PartenaireController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/partenaire']], [], []],
    'partenaire_delete' => [['id'], ['_controller' => 'App\\Controller\\PartenaireController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/partenaire']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\SecurityController::register'], [], [['text', '/api/register']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/api/login_check']], [], []],
    'user_index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/']], [], []],
    'user_new' => [[], ['_controller' => 'App\\Controller\\UserController::ajout'], [], [['text', '/user/new']], [], []],
    'user_show' => [['id'], ['_controller' => 'App\\Controller\\UserController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
    'user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
    'user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
    'api_entrypoint' => [['index', '_format'], ['_controller' => 'api_platform.action.entrypoint', '_format' => '', '_api_respond' => 'true', 'index' => 'index'], ['index' => 'index'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', 'index', 'index', true], ['text', '/api']], [], []],
    'api_doc' => [['_format'], ['_controller' => 'api_platform.action.documentation', '_format' => '', '_api_respond' => 'true'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/api/docs']], [], []],
    'api_jsonld_context' => [['shortName', '_format'], ['_controller' => 'api_platform.jsonld.action.context', '_format' => 'jsonld', '_api_respond' => 'true'], ['shortName' => '.+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '.+', 'shortName', true], ['text', '/api/contexts']], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], []],
];
