<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXFBe4BX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXFBe4BX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXFBe4BX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXFBe4BX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXFBe4BX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XFBe4BX',
    'container.build_id' => '5ba6e4f6',
    'container.build_time' => 1568195087,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXFBe4BX');
